board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("crud.urls")), 
]

crud/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "crud"

urlpatterns = [

    # 게시글
    path("", views.layout, name='layout'),
    path('home/', views.home, name='home'),
    path('new/', views.new, name = 'new'),
    path('create/', views.create, name = 'create'),
    path('newblog/', views.blogform, name = 'newblog'),
    path('edit/<int:pk>/', views.edit, name = 'edit'),
    path('remove/<int:pk>/', views.remove, name = 'remove'),
    
    # 댓글
    path('home/<int:pk>/', views.detail, name = 'detail'),
    path('comment_update/<int:pk>/', views.comment_update, name = 'comment_update'),
    path('comment_delete/<int:pk>/', views.comment_delete, name = 'comment_delete'),

    # 해시태그
    path('hashtag/', views.hashtagform, name="hashtag"),
    path('search/<int:hashtag_id>/', views.search, name="search"),

    # extra 페이지
    path('login/', views.login, name = 'login'),
    path('register/', views.register, name = 'register'),
    path('tables/', views.tables, name = 'tables'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to='image/', blank=True)
    

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:100]

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Comment(models.Model):
    Blog_pk = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name ="comments")
    comment_text = models.CharField(max_length=50)

    def __str__(self):
        return self.comment_text

crud/forms.py
from django import forms
from .models import Blog, Comment,Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','body','hashtags', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': '제목.'}),
            
        }
        
        labels = {
            'title' : '제목',
            'body' : '내용', 
            'image' : '이미지'       
            }

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Hashtag.'}),
        }
        
        labels = {
            'name' : '해시태그',     
            }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]
        widgets = {
            'comment_text': forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': '댓글 등록'}),
            
        }
        
        labels = {
            'comment_text' : '댓글',       
            }

crud/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from .forms import BlogForm, CommentForm, HashtagForm
from .models import Blog, Comment, Hashtag


# index페이지
def layout(request):
        return render(request, 'crud/layout.html')

# 전체글 보여주는 페이지
def home(request):
        blogs = Blog.objects
        hashtags = Hashtag.objects
        return render(request, 'crud/home.html', {'blogs': blogs, 'hashtags': hashtags})

#hashtag 검색
def search(request, hashtag_id):
        hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
        return render(request, 'crud/search.html', {'hashtag': hashtag })

# 새글 등록
def new(request):
        return render(request, 'crud/new.html')

def create(request):
        blog = Blog()
        blog.title = request.GET['title']
        blog.body = request.GET['body']
        blog.pub_date = timezone.datetime.now()
        blog.save()
        return redirect('crud:home')

def blogform(request, blog=None):
        if request.method == 'POST':
                form = BlogForm(request.POST, request.FILES, instance=blog)
                if form.is_valid():
                        blog = form.save(commit=False)
                        blog.pub_date = timezone.now()
                        blog.save()
                        form.save_m2m() 
                        return redirect('crud:home')
        else:
                form = BlogForm(instance=blog)
                return render(request, 'crud/new.html', {'form':form})      

#hashtagForm 커즈마이징
def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'crud/newHashtag.html', {'form':form, "error_message":error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
                return redirect('crud:home')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'crud/newHashtag.html', {'form':form})

# 글수정
def edit(request, pk):
        blog = get_object_or_404(Blog, pk=pk)
        return blogform(request, blog)

# 글삭제
def remove(request, pk):
        blog = get_object_or_404(Blog, pk=pk)
        blog.delete()
        return redirect('crud:home')

# 글 댓글 상세보기 기능
def detail(request, pk):
        blog = get_object_or_404(Blog, pk=pk)
        if request.method == "POST":
                form = CommentForm(request.POST)
                if form.is_valid():
                        comment = form.save(commit=False)
                        comment.Blog_pk = blog
                        comment.comment_text = form.cleaned_data["comment_text"]
                        comment.save()
                        return redirect("crud:detail", blog.pk)
        else:
                form = CommentForm()
                return render(request, "crud/detail.html", {"blog" : blog, "form" : form})


#댓글 수정
def comment_update(request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        blog = comment.Blog_pk
        if request.method == "POST":
                form = CommentForm(request.POST, instance=comment)
                if form.is_valid():
                        comment = form.save(commit=False)
                        comment.Blog_pk = blog
                        comment.comment_text = form.cleaned_data["comment_text"]
                        comment.save()
                        return redirect("crud:detail", blog.pk)
        else:
                form = CommentForm(instance=comment)
                return render(request, "crud/newComment.html", {'form' : form,})

#댓글 삭제
def comment_delete(request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        blog = comment.Blog_pk
        comment.delete()
        return redirect("crud:detail", blog.pk)



# 부가기능 
def login(request):
        return render(request, 'crud/login.html')

def register(request):
        return render(request, 'crud/register.html')

def tables(request):
        return render(request, 'crud/tables.html')

crud/templates/crud/detail.html
{% extends 'crud/layout.html' %}

{% block content %}
<div class="container-fluid">
        
        <div class="card mb-4 py-3 border-bottom-warning">
                <div class="card-body">
                      {% for hashtag in blog.hashtags.all %}
                      <span style="color : cornflowerblue">{{ hashtag.name }}</span>
                      {% endfor %}
                      <br>
                      
                      {% if blog.image %}
                        <img class="card-img-top" src= "{{ blog.image.url }}" alt ="Card img cap" style="width: 300px; height: 300px">
                      {% endif %}
                        <h1> 글 제목 : {{ blog.title }}</h1>
                        <h2> 글 내용 : {{ blog.body }} </h2>
                        <p> 만든 날짜 : {{ blog.pub_date }}</p>
                        <a href="{%url 'crud:edit' pk=blog.pk %}" class="btn btn-success btn-circle">
                            <i class="fas fa-check"></i>
                        </a>
                        <a href="{%url 'crud:remove' pk=blog.pk%}" class="btn btn-danger btn-circle">
                            <i class="fas fa-trash"></i>
                        </a>
                </div>
            
                    
        </div>
        <br>
        <div class="row">
        {% for comment in blog.comments.all %}
        
        <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">댓글</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ comment.comment_text }}</div>
                      </div>
                      <div class="col-auto">
                            <a href="{%url 'crud:comment_update' pk=comment.pk %}" class="btn btn-success btn-circle">
                                    <i class="fas fa-check"></i>
                                  </a>
                            <a href="{%url 'crud:comment_delete' pk=comment.pk %}" class="btn btn-danger btn-circle">
                                        <i class="fas fa-trash"></i>
                            </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            
        {% endfor %}
        </div>
        <form method="post">
            {% csrf_token %}
            {{form.as_table}}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    
{% endblock %}

crud/templates/crud/edit.html
{% extends 'crud/layout.html' %}

{% block content %}
 
<form method='POST'>
        {% csrf_token %}
        {{form.as_table}}
    <button class="btn-default" type="submit" value="save"></button>
</form>
{% endblock %}

crud/templates/crud/home.html
{% extends 'crud/layout.html' %}
{% block content %}
  <!-- Custom styles for this page -->
<div class="container-fluid">
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              
                <div class="row">
                  <div class="col-sm-6">
              <h6 class="m-0 font-weight-bold text-primary">게시판 CRUD</h6>
              </div>
              <div class="col-sm-6">
                
                  <div class="pull-right">
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  #
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {% for hashtag in hashtags.all %}
                  <a class="dropdown-item" href="{% url 'crud:search' hashtag.id %}">{{ hashtag.name }}</a>
                    {% endfor %}
                </div>
                </div>
              </div>
              </div>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>글번호</th>
                        <th>제목</th>
                        <th>내용</th>
                        <th>날짜</th>
                        <th>수정</th>
                        <th>삭제</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>글번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </tfoot>
                  <tbody>
                      {% for blog in blogs.all %}
                    <tr>
                      <td><a href="{%url 'crud:detail' pk=blog.pk %}"> {{ blog.pk }} </a></td>
                      <td>{{ blog.title }}</td>
                      <td>{{ blog.body }}</td>
                      <td>{{ blog.pub_date }}</td>
                      <td style="text-align:center">
                        <a href="{% url 'crud:edit' pk=blog.pk %}" class="btn btn-success btn-circle">
                          <i class="fas fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                          <a href="{%url 'crud:remove' pk=blog.pk %}" class="btn btn-danger btn-circle">
                              <i class="fas fa-trash"></i>
                          </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
      {% endblock %}

crud/templates/crud/layout.html
{% extends 'index.html' %}

crud/templates/crud/new.html
{% extends 'crud/layout.html' %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-sm-12">        
    <h1>게시판 글쓰기</h1>
</div>

    
    <form method='POST' enctype ="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
       &nbsp;  &nbsp;  &nbsp;  &nbsp;
       <input class="btn btn-dark" type="submit" value="작성하기">
    </form>
</div>

</div>
{% endblock %}

crud/templates/crud/newComment.html
{% extends 'crud/layout.html' %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-sm-12">        
    <h1>댓글쓰기</h1>
</div>

    
    <form method='POST'>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
       &nbsp;  &nbsp;  &nbsp;  &nbsp;
       <input class="btn btn-dark" type="submit" value="작성하기">
    </form>
</div>

</div>
{% endblock %}

crud/templates/crud/newHashtag.html
{% extends 'crud/layout.html' %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-sm-12">        
    <h1>New HashTag</h1>
</div>

    {{ error_message }}
    <br>
    <form method='POST'>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
       &nbsp;  &nbsp;  &nbsp;  &nbsp;
       <input class="btn btn-dark" type="submit" value="작성하기">
    </form>
</div>

</div>
{% endblock %}

crud/templates/crud/search.html
{% extends 'crud/layout.html' %}
{% block content %}
  <!-- Custom styles for this page -->
<div class="container-fluid">
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">게시판 with. {{ hashtag.name }}</h6>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>글번호</th>
                        <th>제목</th>
                        <th>내용</th>
                        <th>날짜</th>
                        <th>수정</th>
                        <th>삭제</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>글번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </tfoot>
                  <tbody>
                      {% for blog in hashtag.blog_set.all %}
                    <tr>
                      <td><a href="{%url 'crud:detail' pk=blog.pk %}"> {{ blog.pk }} </a></td>
                      <td>{{ blog.title }}</td>
                      <td>{{ blog.body }}</td>
                      <td>{{ blog.pub_date }}</td>
                      <td style="text-align:center">
                        <a href="{%url 'crud:edit' pk=blog.pk %}" class="btn btn-success btn-circle">
                          <i class="fas fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                          <a href="{%url 'crud:remove' pk=blog.pk %}" class="btn btn-danger btn-circle">
                              <i class="fas fa-trash"></i>
                          </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
      {% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>현수쓰</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'crud:layout' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">현수쓰 <sup>KHS</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'crud:layout' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>HOME</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Board crud 
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>게시판</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">board ex) :</h6>
            <a class="collapse-item" href="{% url 'crud:newblog' %}">게시판 작성하기</a>
            <a class="collapse-item" href="{% url 'crud:home' %}">게시판 전체보기</a>
            <a class="collapse-item" href="{% url 'crud:hashtag' %}">해시태그 작성하기</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        design files
      </div>


      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crud:tables' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">현수쓰</span>
                <img class="img-profile rounded-circle" src="{% static 'img/logo.jpg' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="{% url 'crud:register' %}">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  register
                </a>
                <a class="dropdown-item" href="{% url 'crud:login' %}">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                   login
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          
       

            {% block content %}
            
              <div class="row">
              <br>
            <div class="col-sm-4">
                    <article>
                      <h3 class="C_name">Photo</h3>
                      <img class="art_img" src="{% static 'img/1.JPG' %}" alt="현수쓰_하루를기록하다" style="width: 310px; height: 310px;">
                      <p class="C_into">
                        MOON <br>
                      취미는 달사진 찍기 <br>
                      인스타 갬성 사진 찍기 <br>
                    </article>
                </div>
      
              <div class="col-sm-4">
                 <article>
                  <h3 class="C_name">Travel</h3>
                  <img class="art_img" src="{% static 'img/2.JPG' %}" alt="현수쓰_여행" style="width: 310px; height: 310px;">
                  <p class="C_into">
                    Budapest<br>
                    세체니온천 <br>
                    현수쓰 시그니처 포즈
                  </p>
                 </article>
              </div>
              <div class="col-sm-4">
                <article>
                  <h3 class="C_name">Pet</h3>
                  <img class="art_img" src="{% static 'img/3.JPG' %}" alt="현수쓰_댕댕이" style="width: 310px; height: 310px;">
                  <p>
                    포메라니안 2마리 <br>
                    뵈뵈 / 번개 <br> 
                    천둥(입양 보냄)
                  </p>
                </article>
            </div>
            <div class="col-sm-6">
                <h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-------------------</h1>
                  <h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 하루를 기록하다 </h1>
                <h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-------------------</h1>
            </div>
            <div class="col-sm-6">
                <h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-----------------------</h1>
                  <h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  instagram : khs9628 </h1>
                <h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-----------------------</h1>
            </div>

            </div>
            </div>
          </div>
            {% endblock %}
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; likeLion 현수쓰 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="#">Logout</a>
        </div>
      </div>
    </div>
  </div>


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
  
  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>